In [1]:
import torch
import numpy as np
import os

In [14]:
pathReq=os.getcwd()+'/'
# stats=np.load(pathReq+'allStats20210531BvsP.npy')
stats=np.load(pathReq+'allStats20210609BvsP.npy')

forInference=np.load(pathReq+'statsForInference.npy')
stats.shape,forInference.shape

((5202, 47), (79, 46))

In [15]:
from sklearn.utils import shuffle

stats=shuffle(stats)

In [16]:
# h=['PA','AB','R','H','2B','3B','HR',
#            'RBI','BB','IBB','SO','HBP','SH','SF','GDP','SB','CS']#batting only
# # hP=['Dec','IP','H_','R_','ER','BB_','SO_','HR_','HBP_','AB_','2B_','3B_','IBB_','Pit','Str','StL','StS']#had to add underscores to some to separate from h
# hP=['W','IP','H_', 'R_', 'ER_', 'BB_', 'SO_', 'HR_', 'HBP_', 'AB_', '2B_', '3B_', 'IBB_','Pit', 'Str', 'StL', 'StS']
# hBvsP=['PA2','AB2','H2', '1B2','2B2','3B2','HR2','BB2','SO2','AVG2','OBP2','SLG2'] #BvsP
# hTotal=h+hP+hBvsP



# m=dict()

# for i, hh in enumerate(hTotal):
#     m[hh]=i
    
# print(m)

# stats=stats[np.where(stats[:,m['PA']]>0 )[0]]
# stats=stats[np.where(stats[:,m['IP']]>0)[0]]
# stats=stats[np.where(stats[:,m['PA2']]>0)[0]]

# forInference=forInference[np.where(forInference[:,m['PA']]>0 )[0]]
# forInference=forInference[np.where(forInference[:,m['IP']]>0)[0]]
# forInference=forInference[np.where(forInference[:,m['PA2']]>0)[0]]

# toCount=hTotal

# # toCount=['PA','AB','R','H','2B','3B','HR',
# #          'PA2','AB2','H2', '1B2','2B2','3B2','HR2','BB2','SO2'
# #         ]


# finalFeatures=np.zeros((stats.shape[0],len(toCount)))
# finalInference=np.zeros((forInference.shape[0],len(toCount)))
# for i, cat in enumerate(toCount):
#     if cat in h: # to normalize hitting stats by PA
#         finalFeatures[:,i]=stats[:, m[cat]]/stats[:, m['PA']]
#         finalInference[:,i]=forInference[:,m[cat]]/forInference[:, m['PA']]
#     if cat in hP: # to normalize pitching stats by IP
#         finalFeatures[:,i]=stats[:, m[cat]]/stats[:, m['IP']]
#         finalInference[:,i]=forInference[:,m[cat]]/forInference[:, m['IP']]
#     if cat in hBvsP: # to normalize BvsP stats by PA2
#         finalFeatures[:,i]=stats[:, m[cat]]/stats[:, m['PA2']]
#         finalInference[:,i]=forInference[:,m[cat]]/forInference[:, m['PA2']]
    

In [17]:
def normStats(stats, forInference):
    
    h=['PA','AB','R','H','2B','3B','HR',
           'RBI','BB','IBB','SO','HBP','SH','SF','GDP','SB','CS']#batting only
    # hP=['Dec','IP','H_','R_','ER','BB_','SO_','HR_','HBP_','AB_','2B_','3B_','IBB_','Pit','Str','StL','StS']#had to add underscores to some to separate from h
    hP=['W','IP','H_', 'R_', 'ER_', 'BB_', 'SO_', 'HR_', 'HBP_', 'AB_', '2B_', '3B_', 'IBB_','Pit', 'Str', 'StL', 'StS']
    hBvsP=['PA2','AB2','H2', '1B2','2B2','3B2','HR2','BB2','SO2','AVG2','OBP2','SLG2'] #BvsP
    hTotal=h+hP+hBvsP
    m=dict()
    for i, hh in enumerate(hTotal):
        m[hh]=i
    print(m)
    hTotal=h+hP+hBvsP
    toCount=hTotal

    toCount=h+hP#['PA','AB','R','H','2B','3B','HR','RBI','BB']
             
    
    finalFeatures=np.zeros((stats.shape[0],len(toCount)))
    finalInference=np.zeros((forInference.shape[0],len(toCount)))     
    
    
    for r in range(finalFeatures.shape[0]):        
        for i, cat in enumerate(toCount):
            if cat in h: # to normalize hitting stats by PA
                if stats[r, m['PA']]>0:
                    finalFeatures[r,m[cat]]=stats[r, m[cat]]/stats[r, m['PA']] 
                else:
                    finalFeatures[r,m[cat]]=stats[r, m[cat]]
            if cat in hP: # to normalize pitching stats by IP
                if stats[r, m['IP']]>0:
                    finalFeatures[r,m[cat]]=stats[r, m[cat]]/stats[r, m['IP']]  
                else:
                    finalFeatures[r,m[cat]]=stats[r, m[cat]]
            if cat in hBvsP: # to normalize BvsP stats by PA2
                if stats[r, m['PA2']]>0:
                    finalFeatures[r,m[cat]]=stats[r, m[cat]]/stats[r, m['PA2']]
                else:
                    finalFeatures[r,m[cat]]=stats[r, m[cat]]
                
    for r in range(finalInference.shape[0]):
        for i, cat in enumerate(toCount):            
            if cat in h: # to normalize hitting stats by PA                
                if forInference[r, m['PA']]>0:
                    finalInference[r,m[cat]]=forInference[r,m[cat]]/forInference[r, m['PA']]
                else:
                    finalInference[r,m[cat]]=forInference[r,m[cat]]
            if cat in hP: # to normalize pitching stats by IP                
                if forInference[r, m['IP']]>0:
                    finalInference[r,m[cat]]=forInference[r,m[cat]]/forInference[r, m['IP']]
                else:
                    finalInference[r,m[cat]]=forInference[r,m[cat]]
            if cat in hBvsP: # to normalize BvsP stats by PA2      
                if forInference[r, m['PA2']]>0:
                    finalInference[r,m[cat]]=forInference[r,m[cat]]/forInference[r, m['PA2']]
                else:
                    finalInference[r,m[cat]]=forInference[r,m[cat]]

    return finalFeatures, finalInference

finalFeatures, finalInference=normStats(stats, forInference)



    

{'PA': 0, 'AB': 1, 'R': 2, 'H': 3, '2B': 4, '3B': 5, 'HR': 6, 'RBI': 7, 'BB': 8, 'IBB': 9, 'SO': 10, 'HBP': 11, 'SH': 12, 'SF': 13, 'GDP': 14, 'SB': 15, 'CS': 16, 'W': 17, 'IP': 18, 'H_': 19, 'R_': 20, 'ER_': 21, 'BB_': 22, 'SO_': 23, 'HR_': 24, 'HBP_': 25, 'AB_': 26, '2B_': 27, '3B_': 28, 'IBB_': 29, 'Pit': 30, 'Str': 31, 'StL': 32, 'StS': 33, 'PA2': 34, 'AB2': 35, 'H2': 36, '1B2': 37, '2B2': 38, '3B2': 39, 'HR2': 40, 'BB2': 41, 'SO2': 42, 'AVG2': 43, 'OBP2': 44, 'SLG2': 45}


In [18]:
h=['PA','AB','R','H','2B','3B','HR',
       'RBI','BB','IBB','SO','HBP','SH','SF','GDP','SB','CS']#batting only
# hP=['Dec','IP','H_','R_','ER','BB_','SO_','HR_','HBP_','AB_','2B_','3B_','IBB_','Pit','Str','StL','StS']#had to add underscores to some to separate from h
hP=['W','IP','H_', 'R_', 'ER_', 'BB_', 'SO_', 'HR_', 'HBP_', 'AB_', '2B_', '3B_', 'IBB_','Pit', 'Str', 'StL', 'StS']
hBvsP=['PA2','AB2','H2', '1B2','2B2','3B2','HR2','BB2','SO2','AVG2','OBP2','SLG2'] #BvsP
hTotal=h+hP+hBvsP
m=dict()
for i, hh in enumerate(hTotal):
    m[hh]=i
        
# finalFeatures[np.where(finalFeatures[:,m['PA2']]==0)].shape

In [7]:
# finalFeatures[-10:]

In [19]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

features=torch.tensor(finalFeatures) #torch.tensor(stats[:,skippingFrom:skippingTo])
labels=torch.tensor(stats[:,-1])

forInferenceStats=torch.tensor(finalInference) #torch.tensor(forInference[:,skippingFrom:skippingTo])

pctTotal=(1-torch.mean(labels))*2
finalNo=(features.size()[0]*pctTotal).int()

balancedFeatures=features
balancedLabels=labels
# balancedFeatures=torch.zeros(0,features.size()[1])
# balancedLabels=torch.zeros(0,1)

# c0=0
# c1=0

# for smpl, l in enumerate(labels):
#   if l==1 and c1<(finalNo//2):
#     #balancedFeatures[smpl]=features[smpl]
#     balancedFeatures=np.vstack((balancedFeatures, features[smpl]))
#     balancedLabels=np.vstack((balancedLabels, l))
# #     balancedLabels[smpl]=l
#     c1+=1
#   if l==0 and (c1+c0)<finalNo:
#     balancedFeatures=np.vstack((balancedFeatures, features[smpl]))
#     balancedLabels=np.vstack((balancedLabels, l))
#     c0+=1

   
X_train, X_test, y_train, y_test = train_test_split(torch.tensor(balancedFeatures), torch.tensor(balancedLabels.squeeze()), test_size=0.2, random_state=42)

# X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size=0.1, random_state=42)

scaler = StandardScaler()

x_norm=torch.tensor(scaler.fit_transform(X_train))

x_norm_test=torch.tensor(scaler.fit_transform(X_test))

inference_norm=torch.tensor(scaler.fit_transform(forInferenceStats))


/home/adimn/anaconda3/envs/venv-base/lib/python3.7/site-packages/ipykernel_launcher.py:34: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).


In [20]:
# y_train

In [21]:
torch.mean(y_train),torch.mean(y_test)

(tensor(0.6688, dtype=torch.float64), tensor(0.6244, dtype=torch.float64))

In [22]:
# balancedFeatures[:100], finalNo,pctTotal,c1,c0,np.mean(balancedLabels)

In [23]:
x_norm.shape,x_norm_test.shape,inference_norm.shape

(torch.Size([4161, 34]), torch.Size([1041, 34]), torch.Size([79, 34]))

In [ ]:
from torch import nn
import torch.optim as optim

device = torch.device('cpu')
if torch.cuda.is_available():
    device = torch.device('cuda')

net = nn.Sequential(
      nn.Linear(features.shape[1], 5),
      nn.ReLU(),    
      nn.Linear(5,10),
      nn.ReLU(),
      nn.Linear(10,1),    
      #nn.Dropout(p=0.5),
      nn.Sigmoid(),
      ).to(device)

net=net.double()

losses=[]

correct=0
count=0

def train_gen(feat,lbl, batch=4):
  fBatch=[]#torch.zeros(batch, feat.size()[1])
  lBatch=[]#torch.zeros(lbl)
  for i, f in enumerate(feat):   
    fBatch.append(f.numpy())
    lBatch.append(lbl[i].numpy())
    if len(fBatch)==batch:
      yield fBatch, lBatch
      fBatch,lBatch=[],[]
  
batchSize=1

epochs=100
optimizer = optim.Adam(net.parameters(), lr=1e-3, weight_decay=1e-4)
#(optimizer, step_size, gamma=0.1, last_epoch=-1, verbose=False)
scheduler = torch.optim.lr_scheduler.StepLR(optimizer, 100, gamma=0.5, last_epoch=-1)

criterion = nn.BCELoss()  

for epoch in range(epochs):
    #gen=train_gen(X_train,y_train,batchSize)
    for sample, label in zip(x_norm, y_train):
    #for sample, label in gen:
        sample=torch.tensor(sample).to(device)
        label=torch.tensor(label).to(device)
        #label=torch.from_numpy(np.array(label)).to(device)
        sample=sample.double()
        label=label.double()
        
        output=net(sample)        
        net.zero_grad()
        target = label
        #target = target.view(-1, 1)  # make it the same shape as output #this is for batches
        target = target.view(1)  # make it the same shape as output 
        #print('pred:',output, 'pred shape:',output.shape, 'label:', target, 'label shape:', target.shape)            

        # in your training loop:
        optimizer.zero_grad()   # zero the gradient buffers

        loss = criterion(output, target)
        loss.backward()
        optimizer.step()    # Does the update
        
        
        losses.append(loss)
        count+=batchSize
        if (output>0.5 and label==1) or (output<=0.5 and label==0):
              correct+=1
    
#     scheduler.step()
    acc=correct/count
    
    print('epoch=' ,epoch, 'avg loss=', torch.mean(torch.tensor(losses)), 'acc = ', acc)


/home/adimn/anaconda3/envs/venv-base/lib/python3.7/site-packages/ipykernel_launcher.py:48: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
/home/adimn/anaconda3/envs/venv-base/lib/python3.7/site-packages/ipykernel_launcher.py:49: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).


epoch= 0 avg loss= tensor(0.6438, dtype=torch.float64) acc =  0.6560922855082912
epoch= 1 avg loss= tensor(0.6384, dtype=torch.float64) acc =  0.6630617639990387
epoch= 2 avg loss= tensor(0.6360, dtype=torch.float64) acc =  0.6650644877032764
epoch= 3 avg loss= tensor(0.6346, dtype=torch.float64) acc =  0.6665465032444124
epoch= 4 avg loss= tensor(0.6335, dtype=torch.float64) acc =  0.6672915164623888
epoch= 5 avg loss= tensor(0.6326, dtype=torch.float64) acc =  0.6679083553632941
epoch= 6 avg loss= tensor(0.6318, dtype=torch.float64) acc =  0.6684519517973014
epoch= 7 avg loss= tensor(0.6311, dtype=torch.float64) acc =  0.6685892814227349
epoch= 8 avg loss= tensor(0.6304, dtype=torch.float64) acc =  0.6688563112499666
epoch= 9 avg loss= tensor(0.6298, dtype=torch.float64) acc =  0.6690218697428503
epoch= 10 avg loss= tensor(0.6292, dtype=torch.float64) acc =  0.6692010224814839
epoch= 11 avg loss= tensor(0.6287, dtype=torch.float64) acc =  0.6694304253785148
epoch= 12 avg loss= tensor

In [ ]:
ind=100

for x, y in zip(x_norm[:ind], y_train[:ind]):
    print(y)

In [ ]:
test=np.load(pathReq+'allStats20210528BvsP.npy')
testfeats=test[:,:-1]

finalFeatures, testfeats=normStats(stats, testfeats)

x_norm_test2=torch.tensor(scaler.fit_transform(testfeats))
y_test2=test[:,-1]

In [72]:
# from datetime import datetime
# dateReq=datetime.today().strftime('%Y-%m-%d')
# PATH=pathReq + '/savedModels/Features46(3-5-1)'+dateReq+'.pth'

# # for param_tensor in net.state_dict():
# #     print(param_tensor, "\t", net.state_dict()[param_tensor])

# torch.save(net.state_dict(), PATH)
# net.load_state_dict(torch.load(PATH))


<All keys matched successfully>

In [32]:
with torch.no_grad():
    net.eval()
    net.cpu()
    indices=350
    net(x_norm[:indices].cpu()),y_train[:indices],net(x_norm_test[:indices].cpu()),y_test[:indices]

    # for i in range(indices):
    #   print('pred=', net(x_norm[i].cpu()).item(),'label=', y_train[i])
    
    c=0
    tp=0
    for i in range(indices):
      pred_score=net(x_norm_test[i].cpu()).item()
      if pred_score >0.9:
        print('pred test=', pred_score ,'label=', y_test[i])
        if pred_score-y_test[i]<0.5:
            tp+=1            
        c+=1
tp, c, (tp/c)

pred test= 0.9430216678264681 label= tensor(1., dtype=torch.float64)
pred test= 0.9824384272298328 label= tensor(1., dtype=torch.float64)
pred test= 0.9267440607666423 label= tensor(1., dtype=torch.float64)
pred test= 0.9233528852044969 label= tensor(0., dtype=torch.float64)
pred test= 0.9114851432574353 label= tensor(0., dtype=torch.float64)
pred test= 0.9687412599609398 label= tensor(1., dtype=torch.float64)
pred test= 0.9389194672816609 label= tensor(1., dtype=torch.float64)
pred test= 0.9520765150690819 label= tensor(1., dtype=torch.float64)
pred test= 0.9456409786917822 label= tensor(1., dtype=torch.float64)
pred test= 0.947383032100556 label= tensor(1., dtype=torch.float64)
pred test= 0.9859727059948877 label= tensor(0., dtype=torch.float64)
pred test= 0.9001065575941765 label= tensor(0., dtype=torch.float64)
pred test= 0.9908971058783455 label= tensor(1., dtype=torch.float64)
pred test= 0.9999433368889236 label= tensor(0., dtype=torch.float64)
pred test= 0.9248123874926275 label

(13, 25, 0.52)

In [51]:
net.eval()
net.cpu()
preds=net(inference_norm)

In [52]:
inference_norm.shape

torch.Size([39, 33])

In [53]:

preds.shape

torch.Size([39, 1])

In [50]:
pList=[['Miguel Rojas', 'Miami'],
 ['Austin Hays', 'Baltimore'],
 ['Raimel Tapia', 'Colorado'],
 ['Marcus Semien', 'Toronto'],
 ['Cedric Mullins', 'Baltimore'],
 ['Jake Cronenworth', 'San Diego'],
 ['Yoan Moncada', 'Chicago'],
 ['Teoscar Hernandez', 'Toronto'],
 ['Dylan Carlson', 'St. Louis'],
 ['Trey Mancini', 'Baltimore'],
 ['Tommy Edman', 'St. Louis'],
 ['Bo Bichette', 'Toronto'],
 ['Ramon Laureano', 'Oakland'],
 ['Kolten Wong', 'Milwaukee'],
 ['Randal Grichuk', 'Toronto'],
 ['Robbie Grossman', 'Detroit'],
 ['Nolan Arenado', 'St. Louis'],
 ['Tim Anderson', 'Chicago'],
 ['Vladimir Guerrero Jr.', 'Toronto']]



In [52]:
from datetime import datetime
print(datetime.today().strftime('%Y-%m-%d'))
nnOut=[]
for i, ind in enumerate(torch.topk(preds.reshape(1,preds.shape[0]),10)[1][0]):  
  nnOut.append(pList[ind])
  print(pList[ind],torch.topk(preds.reshape(1,preds.shape[0]),10)[0][0][i].item())

2021-05-24
['Marcus Semien', 'Toronto'] 0.9260356487699175
['Randal Grichuk', 'Toronto'] 0.8976579394915949
['Ramon Laureano', 'Oakland'] 0.6988358214337181
['Bo Bichette', 'Toronto'] 0.656616436729234
['Teoscar Hernandez', 'Toronto'] 0.6280565786076028
['Nolan Arenado', 'St. Louis'] 0.6077291051733582
['Cedric Mullins', 'Baltimore'] 0.04456414760401088
['Raimel Tapia', 'Colorado'] 0.029471240817665074
['Jake Cronenworth', 'San Diego'] 0.025413258555440132
['Miguel Rojas', 'Miami'] 0.0012692695407037352


In [ ]:
len(pList)

49

In [133]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression(random_state=0, max_iter=1000).fit(x_norm, y_train)

In [134]:
clf.score(x_norm_test, y_test)

0.6528662420382165

In [24]:
from datetime import datetime
print(datetime.today().strftime('%Y-%m-%d'))

lrOut=[]
for i, pred in enumerate(clf.predict_proba(inference_norm)[:,1][np.argsort(-clf.predict_proba(inference_norm)[:,1])][:10]):  
  lrOut.append(pList[i])
  print(pList[i], pred)

2021-05-15
['Paul Goldschmidt', 'St. Louis'] 0.999780017203643
['Rafael Devers', 'Boston'] 0.9848612150580556
['Randal Grichuk', 'Toronto'] 0.9346816196472018
['Giancarlo Stanton', 'New York'] 0.9259634913698378
['Andrew Benintendi', 'Kansas City'] 0.8824150199235107
['Jesus Aguilar', 'Miami'] 0.8433218626593961
['Shohei Ohtani', 'Los Angeles'] 0.8396202610265788
['Trey Mancini', 'Baltimore'] 0.8273806263552075
['Rhys Hoskins', 'Philadelphia'] 0.7735909562856644
['Corey Seager', 'Los Angeles'] 0.7596874128563706


In [27]:
for o in nnOut:
  if o in lrOut:
    print(o)

['Paul Goldschmidt', 'St. Louis']
['Corey Seager', 'Los Angeles']
['Randal Grichuk', 'Toronto']
['Giancarlo Stanton', 'New York']
['Rhys Hoskins', 'Philadelphia']
['Rafael Devers', 'Boston']
['Jesus Aguilar', 'Miami']


In [ ]:
# 2021-05-12
# ['Jake Cronenworth', 'San Diego'] 0.9951982878094792
# ['Paul Goldschmidt', 'St. Louis'] 0.9885262239419107
# ['Yermin Mercedes', 'Chicago'] 0.9743571206807747
# ['Carlos Santana', 'Kansas City'] 0.9727445792429186
# ['Mike Trout', 'Los Angeles'] 0.9636184834153763
# ['Austin Riley', 'Atlanta'] 0.9586897621663748
# ['Randal Grichuk', 'Toronto'] 0.9498869962253059
# ['J.D. Martinez', 'Boston'] 0.9106846220235486
# ['Trey Mancini', 'Baltimore'] 0.8654366296051179
# ['Trent Grisham', 'San Diego'] 0.7794279905260642



In [ ]:
np.argsort(-clf.predict_proba(inference_norm)[:,1]),clf.predict_proba(inference_norm)[:,1],clf.predict_proba(inference_norm)[:,1][np.argsort(-clf.predict_proba(inference_norm)[:,1])]


(array([18,  9, 11, 32, 34, 28, 36, 29, 15,  4, 39,  8,  3, 35,  0, 19, 26,
        33,  2, 13, 21, 42,  6, 14, 30, 38, 41, 40, 37, 31,  7, 25, 17, 10,
        46,  1, 43, 24, 22, 45, 20, 16, 12,  5, 44, 27, 23]),
 array([0.45747394, 0.07671667, 0.42466979, 0.50921759, 0.64018901,
        0.0657057 , 0.26373826, 0.08482591, 0.56207819, 0.8352786 ,
        0.0806784 , 0.83372114, 0.0657057 , 0.37323229, 0.25208786,
        0.66286895, 0.0657057 , 0.08482591, 0.9721208 , 0.44813441,
        0.0657057 , 0.36740579, 0.06914139, 0.0657057 , 0.06914139,
        0.08482591, 0.43756551, 0.0657057 , 0.68468595, 0.66286895,
        0.21396768, 0.08939631, 0.82797847, 0.42979197, 0.71715111,
        0.47543885, 0.66309993, 0.10858724, 0.19750926, 0.62796537,
        0.13930828, 0.18658975, 0.35013712, 0.07651625, 0.0657057 ,
        0.0657057 , 0.07671667]),
 array([0.9721208 , 0.8352786 , 0.83372114, 0.82797847, 0.71715111,
        0.68468595, 0.66309993, 0.66286895, 0.66286895, 0.64018901,
    

In [ ]:
h=['PA','AB','R','H','2B','3B','HR',
           'RBI','BB','IBB','SO','HBP','SH','SF','GDP','SB','CS']#batting only
hBvsP=['PA2','AB2','H2', '1B2','2B2','3B2','HR2','BB2','SO2','AVG2','OBP2','SLG2'] #BvsP

clf.coef_

array([[ 0.15407444,  0.12765536, -0.51097697, -1.28875385, -0.11525518,
        -0.02817996, -0.53926629,  0.40723739,  0.94032604,  0.08294364,
         1.06828656,  0.04501935,  0.        ,  0.53586396,  0.33600777,
        -0.05340233,  0.14588743,  0.59336036]])

In [ ]:
h[8]

'BB'

In [ ]:
y_test[:15]

tensor([1., 0., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0., 1., 1., 1.])

In [ ]:
pctTotal=(1-torch.mean(labels))*2

finalNo=(features.size()[0]*pctTotal).int()

balancedSet=torch.zeros(finalNo,features.size()[1])

for smpl, l in enumerate(labels):
  if l==1 and smpl<(finalNo/2):
    balancedSet[smpl]=features[smpl].copy()
  else:
    balancedSet[smpl]=features[smpl].copy()



IndexError: ignored

In [ ]:
finalNo

tensor(914, dtype=torch.int32)